modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/polvallverdu/xcraft"
license = "Apache 2.0"

[[mods]]
modId = "xcraft"
version = "${version}"
displayName = "xCraft"
authors = "Pol"
description = '''
Speed-up your early game multiplying drops, furnace speed, and more...
'''
logoFile = "assets/xcraft/icon.png"
displayURL = "https://polv.dev"

[[dependencies.xcraft]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.xcraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.xcraft]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
